# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: "Octo STS"
description: |
  This action exchanges the workflow's identity token for a Github App token
  from the Octo STS service, in accordance with the trust policy of the target
  organization or repository.

inputs:
  domain:
    description: |
      The domain of the Octo STS instance to use to federate.
    default: webhooks.build.datadoghq.com

  audience:
    description: |
      The audience of the Octo STS instance to use.
    default: dd-octo-sts

  scope:
    description: |
      The org/repo of the repository to which to request access (legacy endpoint).
      Mutually exclusive with scope_enterprise and scope_organization.
    required: false

  policy:
    description: |
      The name of the trust policy to load from the target repository. The trust policy
      is loaded from https://github.com/{scope} from the file
      .github/chainguard/{identity}.sts.yaml
    required: true

  pool_name:
    description: |
      The name of the application pool to use. When provided, uses the pool endpoint.
      Mutually exclusive with application_id.
    required: false

  application_id:
    description: |
      The specific application ID to use. When provided, uses the pool endpoint.
      Mutually exclusive with pool_name.
    required: false

  scope_enterprise:
    description: |
      Enterprise slug for enterprise-level tokens (pool endpoint only).
      Mutually exclusive with scope and scope_organization.
    required: false

  scope_organization:
    description: |
      Organization name for organization-level tokens (pool endpoint only).
      Mutually exclusive with scope and scope_enterprise.
    required: false

outputs:
  token:
    description: |
      The federated token to use for authentication.
    value: ${{ steps.octo-sts.outputs.token }}

  expires_at:
    description: |
      ISO 8601 timestamp when the token expires (pool endpoint only).
    value: ${{ steps.octo-sts.outputs.expires_at }}

  application_id:
    description: |
      The application ID that issued the token (pool endpoint only).
    value: ${{ steps.octo-sts.outputs.application_id }}

  application_name:
    description: |
      The application name that issued the token (pool endpoint only).
    value: ${{ steps.octo-sts.outputs.application_name }}

runs:
  using: "node20"
  main: "index.js"
  post: "post.js"
