issuer: https://token.actions.githubusercontent.com

subject_pattern: repo:DataDog/dd-octo-sts-action:.*

claim_pattern:
  event_name: (push|pull_request)
  job_workflow_ref: DataDog/dd-octo-sts-action/.github/workflows/test.yml@.*

permissions:
  contents: read
